services:
  - type: web
    name: infinichess
    env: node
    nodeVersion: 22
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
