name = "infinichess"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "infinichess-prod"
route = "infinichess.example.com/*"
zone_id = ""

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["client/**/*.js", "client/**/*.css", "client/**/*.html"]

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js"]
fallthrough = true

[[build.upload.rules]]
type = "Bytes"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.mp3", "**/*.wav"]
fallthrough = true
