name = "infinichess-client"
type = "javascript"
account_id = ""
workers_dev = true

[env.production]
name = "infinichess-prod"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["client/**/*"]

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js"]
fallthrough = true

[[build.upload.rules]]
type = "Bytes"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.mp3", "**/*.wav"]
fallthrough = true
